spring:
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  h2:
    console:
      enabled: true
  data:
    redis:
      repositories:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.amqp: INFO
    org.springframework.rabbit: INFO
messaging:
  enabled: false
